import { Destination } from "@/types";

export const destinationsData: Destination[] = [
  {
    id: "dest-1",
    title: "Amalfi Coast Cliffside Villa",
    country: "Italy",
    region: "europe",
    tagline: "Cascading lemon groves & panoramic Tyrrhenian sea horizons",
    rating: 4.98,
    reviewsCount: 142,
    pricePerNight: 850,
    durationDays: 7,
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    highlights: ["Private Infinity Pool", "Michelin Dining Included", "Yacht Transfer"],
    vibe: "Romantic & Coastal Luxury",
  },
  {
    id: "dest-2",
    title: "Kyoto Arashiyama Bamboo Sanctuary",
    country: "Japan",
    region: "asia",
    tagline: "Serene traditional ryokan amidst ancient bamboo groves",
    rating: 4.96,
    reviewsCount: 98,
    pricePerNight: 1200,
    durationDays: 5,
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    highlights: ["Private Onsen Hot Spring", "Kaiseki Tasting Menu", "Helicopter Airport Shuttle"],
    vibe: "Mindful Tranquility",
  },
  {
    id: "dest-3",
    title: "Bora Bora Overwater Bungalow Suite",
    country: "French Polynesia",
    region: "tropical",
    tagline: "Glass-bottom floor ocean suites with Mount Otemanu backdrop",
    rating: 4.99,
    reviewsCount: 210,
    pricePerNight: 1850,
    durationDays: 10,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    highlights: ["Canoe Breakfast Delivery", "Private Coral Reef Diving", "Personal Butler"],
    vibe: "Pure Tropical Elegance",
  },
  {
    id: "dest-4",
    title: "Zermatt Matterhorn Chalet",
    country: "Switzerland",
    region: "europe",
    tagline: "Ski-in/ski-out chalet featuring panoramic alpine glacier views",
    rating: 4.95,
    reviewsCount: 84,
    pricePerNight: 1400,
    durationDays: 6,
    image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    highlights: ["Private Sauna & Jacuzzi", "Dedicated Ski Concierge", "Fondue & Vintage Cellar"],
    vibe: "Winter Alpine Haven",
  },
  {
    id: "dest-5",
    title: "Patagonia Glacier Eco-Lodge",
    country: "Chile",
    region: "americas",
    tagline: "Untamed wilderness luxury beneath Torres del Paine peaks",
    rating: 4.94,
    reviewsCount: 76,
    pricePerNight: 950,
    durationDays: 8,
    image: "https://images.unsplash.com/photo-1527004013197-933c4bb611b3?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    highlights: ["Puma Tracking Safaris", "Glacier Navigation", "All-Inclusive Chef Specials"],
    vibe: "Raw Wilderness Exploration",
  },
  {
    id: "dest-6",
    title: "Santorini Oia Sunset Penthouse",
    country: "Greece",
    region: "europe",
    tagline: "Iconic whitewashed architecture overlooking Aegean volcanic caldera",
    rating: 4.97,
    reviewsCount: 188,
    pricePerNight: 1100,
    durationDays: 5,
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    highlights: ["Caldera Sunset Deck", "Private Catamaran Cruise", "Sommelier Wine Pairing"],
    vibe: "Caldera Chic",
  },
];
