import { PricingTier } from "@/types";

export const pricingTiers: PricingTier[] = [
  {
    id: "explorer",
    name: "Voyager Pass",
    tagline: "Ideal for frequent luxury leisure travelers seeking exclusive access.",
    priceMonthly: 149,
    priceAnnually: 119,
    popular: false,
    features: [
      "Access to 200+ curated 5-star partner hotels",
      "24/7 AI Itinerary Planner & Agent",
      "Complimentary room upgrade upon availability",
      "Late check-out guarantee (up to 4:00 PM)",
      "Standard airport lounge access passes (6x/yr)",
      "Dedicated chat support (15 min response)",
    ],
    ctaText: "Start 14-Day Free Trial",
    ctaHref: "#booking",
  },
  {
    id: "first-class",
    name: "First Class Pass",
    tagline: "Our flagship membership for global nomads & luxury enthusiasts.",
    priceMonthly: 399,
    priceAnnually: 329,
    popular: true,
    features: [
      "Everything in Voyager Pass",
      "Unlimited Priority Pass™ airport lounge access",
      "Guaranteed room upgrades at check-in",
      "Private jet charter seat sharing network access",
      "24/7 Human Lifestyle Concierge + AI Assistant",
      "$500 annual resort amenity credit",
      "Complimentary private airport transfer (4x/yr)",
    ],
    ctaText: "Claim First Class Access",
    ctaHref: "#booking",
  },
  {
    id: "jetsetter",
    name: "Black Card Jetsetter",
    tagline: "Bespoke invitation-only tier for high-net-worth individuals & founders.",
    priceMonthly: 999,
    priceAnnually: 849,
    popular: false,
    features: [
      "Everything in First Class Pass",
      "Dedicated Personal Executive Travel Manager",
      "Unlimited private jet empty-leg flight alerts",
      "Private island buyout reservations & access",
      "Custom security detail upon request worldwide",
      "Zero cancellation fees & instant refunds",
      "VIP Fast-track customs at 80+ international hubs",
    ],
    ctaText: "Request Membership Invite",
    ctaHref: "#booking",
  },
];
